export const httpCodes = {
    "HTTP_RESPONSE_OK": 200,
    "HTTP_RESPONSE_BAD_REQUEST": 400,
    "HTTP_RESPONSE_UNAUTHORIZED": 401,
    "HTTP_RESPONSE_FORBIDDEN": 403,
    "HTTP_RESPONSE_NOT_FOUND": 404,
    "HTTP_RESPONSE_METHOD_NOT_ALLOWED": 405,
}